# Colors ()
colors:
  # Default colors
  primary:
    background: '#1c1c1c'
    foreground: '#bfbfbf'

    # Bright and dim foreground colors
    #
    # The dimmed foreground color is calculated automatically if it is not present.
    # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
    # is `false`, the normal foreground color will be used.
    #dim_foreground: '#828482'
    #bright_foreground: '#eaeaea'

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor.
  #
  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  #cursor:
  #  text: CellBackground
  #  cursor: CellForeground

  # Vi mode cursor colors
  #
  # Colors for the cursor when the vi mode is active.
  #
  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  #vi_mode_cursor:
  #  text: CellBackground
  #  cursor: CellForeground

  # Selection colors
  #
  # Colors which should be used to draw the selection area.
  #
  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  #selection:
  #  text: CellBackground
  #  background: CellForeground

  # Search colors
  #
  # Colors used for the search bar and match highlighting.
  #
  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  #search:
  #  matches:
  #    foreground: '#000000'
  #    background: '#ffffff'
  #
  #  bar:
  #    background: CellForeground
  #    foreground: CellBackground

  # Normal colors
  normal:
    black:   '#0d0015'
    white:   '#c9c9c9'
    # Saturation 50 ~ 70, Brightness 70 ~ 80
    red:     '#cc5745' # S66 B80
    green:   '#4aba77' # S60 B72
    yellow:  '#c6b44b' # S62 B77
    blue:    '#4071bc' # S65 B73
    magenta: '#c15eb2' # S51 B75
    cyan:    '#59b9c6' # S55 B77

  # Bright colors
  bright:
    black:   '#0d0015'
    white:   '#c9c9c9'
    # Saturation 40 ~ 60, Brightness 60 ~ 70
    red:     '#b24a5a' # S58 B69
    green:   '#acb54d' # S57 B70
    yellow:  '#a88a43' # S60 B65
    blue:    '#5f92ad' # S45 B67
    magenta: '#b26598' # S43 B69
    cyan:    '#46a5aa' # S58 B66

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  #dim:
  #  black:   '#131415'
  #  red:     '#864343'
  #  green:   '#777c44'
  #  yellow:  '#9e824c'
  #  blue:    '#556a7d'
  #  magenta: '#75617b'
  #  cyan:    '#5b7d78'
  #  white:   '#828482'

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #
  # Example:
  #   `- { index: 16, color: '#ff00ff' }`
  #
  #indexed_colors: []
