# Colors ()
colors:
  # Default colors
  primary:
    background: '#000000' # black
    foreground: '#d3d3d3' # lightgray

    # Bright and dim foreground colors
    #
    # The dimmed foreground color is calculated automatically if it is not present.
    # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
    # is `false`, the normal foreground color will be used.
    #dim_foreground: '#828482'
    #bright_foreground: '#eaeaea'

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor.
  #
  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  #cursor:
  #  text: CellBackground
  #  cursor: CellForeground

  # Vi mode cursor colors
  #
  # Colors for the cursor when the vi mode is active.
  #
  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  #vi_mode_cursor:
  #  text: CellBackground
  #  cursor: CellForeground

  # Selection colors
  #
  # Colors which should be used to draw the selection area.
  #
  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  #selection:
  #  text: CellBackground
  #  background: CellForeground

  # Search colors
  #
  # Colors used for the search bar and match highlighting.
  #
  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  #search:
  #  matches:
  #    foreground: '#000000'
  #    background: '#ffffff'
  #
  #  bar:
  #    background: CellForeground
  #    foreground: CellBackground

  # Normal colors
  normal:
    black:   '#000000' # black
    red:     '#ff4500' # orangered
    green:   '#32cd32' # limegreen
    yellow:  '#ffd700' # gold
    blue:    '#87c3fa' # lightskyblue
    magenta: '#ee82ee' # violet
    cyan:    '#40e0d0' # turquoise
    white:   '#d3d3d3' # lightgray

  # Bright colors
  bright:
    black:   '#000000' # black
    red:     '#ff6347' # tomato
    green:   '#9acd32' # yellowgreen
    yellow:  '#daa520' # goldenrod
    blue:    '#87c3fa' # lightskyblue
    magenta: '#ee82ee' # violet
    cyan:    '#48d1cc' # mediumturquoise
    white:   '#d3d3d3' # lightgray

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  #dim:
  #  black:   '#131415'
  #  red:     '#864343'
  #  green:   '#777c44'
  #  yellow:  '#9e824c'
  #  blue:    '#556a7d'
  #  magenta: '#75617b'
  #  cyan:    '#5b7d78'
  #  white:   '#828482'

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #
  # Example:
  #   `- { index: 16, color: '#ff00ff' }`
  #
  #indexed_colors: []
